version: '2'
services:
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    restart: always             # run as a service
    volumes:
      - "./postgresql:/var/lib/postgresql/data"

  odoo10:
    image: odoo:10.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    #tty: true
    command: -- --dev=reload
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service